import os

BASE = "app/src/main/java/com/eltavine/duckdetector"

files = {
    # DashboardUiState
    f"{BASE}/features/dashboard/ui/model/DashboardUiState.kt": [
        ('dangerCount > 0 -> "Danger"', 'dangerCount > 0 -> "Peligro"'),
        ('warningCount > 0 -> "Warning"', 'warningCount > 0 -> "Advertencia"'),
        ('infoErrorCount > 0 -> "Info"', 'infoErrorCount > 0 -> "Información"'),
        ('readyCount == 0 -> "Ready"', 'readyCount == 0 -> "Listo"'),
        ('pendingCount > 0 -> "Pending"', 'pendingCount > 0 -> "Pendiente"'),
        ('joinToString(separator = " and ")', 'joinToString(separator = " y ")'),
        ('"Start with ${', '"Empezar con ${'),
        ('"Review ${', '"Revisar ${'),
        ('" next."', '" a continuación."'),
        (' need more context before treating results as clean."', ' necesitan más contexto antes de tratar los resultados como limpios."'),
        ('"Detector cards will populate as local checks complete."', '"Las tarjetas de detección se poblarán a medida que finalicen las verificaciones locales."'),
        ('"Additional modules are still collecting their local evidence."', '"Los módulos adicionales aún están recolectando su evidencia local."'),
        ('"Use the detector cards below to inspect local evidence in detail."', '"Usá las tarjetas de detección de abajo para inspeccionar la evidencia local en detalle."'),
        ('"Scanned at ${formatDetectedTimeLocal(scanCompletedAtEpochMillis)}\\nTotal time ${formatScanDuration(scanDurationMillis)}"', '"Escaneado el ${formatDetectedTimeLocal(scanCompletedAtEpochMillis)}\\nTiempo total ${formatScanDuration(scanDurationMillis)}"'),
        ('"Security overview"', '"Resumen de seguridad"'),
        ('label = "Danger"', 'label = "Peligro"'),
        ('label = "Warning"', 'label = "Advertencia"'),
        ('label = "Ready"', 'label = "Listo"'),
        ('label = "Pending"', 'label = "Pendiente"'),
        ('"Scan status"', '"Estado del escaneo"'),
        ('"Waiting for detector evidence"', '"Esperando evidencia de los detectores"'),
        ('"Detector cards will expand as modules finish collecting local evidence."', '"Las tarjetas se expandirán a medida que los módulos terminen de recolectar evidencia local."'),
        ('detectorTitle = "Overview"', 'detectorTitle = "Resumen"'),
        ('"No urgent findings in ready modules"', '"Sin hallazgos urgentes en los módulos listos"'),
        ('"Open detector cards below to review detailed local evidence and secondary checks."', '"Abrí las tarjetas de detección para revisar la evidencia local detallada y las verificaciones secundarias."'),
    ],
    # DashboardScreen
    f"{BASE}/features/dashboard/ui/DashboardScreen.kt": [
        ('"Build Time (UTC)"', '"Hora de compilación (UTC)"'),
        ('"Export Report"', '"Exportar Reporte"'),
        ('"Running local checks"', '"Ejecutando verificaciones locales"'),
        ('"Dashboard summary will unlock when the detector cards finish collecting evidence."', '"El resumen del dashboard se desbloqueará cuando las tarjetas terminen de recolectar evidencia."'),
        ('"Priority review queue"', '"Cola de revisión prioritaria"'),
        ('"Report saved"', '"Reporte guardado"'),
        ('DetectionSeverity.DANGER -> "High"', 'DetectionSeverity.DANGER -> "Alto"'),
        ('DetectionSeverity.WARNING -> "Warn"', 'DetectionSeverity.WARNING -> "Adv"'),
        ('DetectionSeverity.INFO -> "Check"', 'DetectionSeverity.INFO -> "Info"'),
        ('DetectionSeverity.ALL_CLEAR -> "Clear"', 'DetectionSeverity.ALL_CLEAR -> "OK"'),
        ('it != "Security overview"', 'it != "Resumen de seguridad"'),
    ],
    # ScanProgressNotificationFormatter
    f"{BASE}/core/notifications/ScanProgressNotificationFormatter.kt": [
        ('"Scanning $clampedReady/$clampedTotal"', '"Escaneando $clampedReady/$clampedTotal"'),
        ('"Danger"', '"Peligro"'),
        ('"Warning"', '"Advertencia"'),
        ('"Info"', '"Información"'),
    ],
    # NativeRootCardModelMapper
    f"{BASE}/features/nativeroot/presentation/NativeRootCardModelMapper.kt": [
        ('"KernelSU and APatch indicators detected"', '"Indicadores de KernelSU y APatch detectados"'),
        ('"Current app already runs in KernelSU su domain"', '"La app ya se ejecuta en el dominio su de KernelSU"'),
        ('"KernelSU detected via ksu_driver"', '"KernelSU detectado via ksu_driver"'),
        ('"KernelSU detected via prctl"', '"KernelSU detectado via prctl"'),
        ('"KernelSU indicators detected"', '"Indicadores de KernelSU detectados"'),
        ('"APatch indicators detected"', '"Indicadores de APatch detectados"'),
        ('"Magisk native indicators detected"', '"Indicadores nativos de Magisk detectados"'),
        ('"Root indicators detected"', '"Indicadores de root detectados"'),
        ('"Isolated mount drift suggests namespace tampering"', '"Deriva de montaje aislado sugiere manipulación de namespace"'),
        ('"Isolated-process namespace drift needs review"', '"La deriva de namespace del proceso aislado requiere revisión"'),
        ('"KernelSU manager weak fingerprint detected"', '"Fingerprint débil del manager de KernelSU detectado"'),
        ('"No native root indicators"', '"Sin indicadores de root nativo"'),
        ('"Native Root scan failed before evidence could be assembled."', '"El escaneo de Root Nativo falló antes de recolectar evidencia."'),
        ('"Read-only ksu_driver hits, direct syscall hits, self-process IOC, root-manager paths, curated runtime residue paths, /data/local/tmp metadata drift, cgroup/process leakage, unexpected root processes, or isolated-process namespace drift indicate active native root infrastructure."',
         '"Detecciones de ksu_driver de solo lectura, syscall directos, IOC del proceso propio, rutas del manager root, rutas de residuo de runtime, deriva de metadatos /data/local/tmp, fuga cgroup/proceso, procesos root inesperados o deriva de namespace indican infraestructura root nativa activa."'),
        ('"Only weaker isolated-process mount drift, manager manifest fingerprints, process, cgroup, kernel, property, or metadata residue surfaced. These are review-worthy, but not as strong as direct native probes."',
         '"Solo surgieron señales más débiles de deriva de montaje de proceso aislado, fingerprints del manifest del manager o residuos de proceso, cgroup, kernel o metadatos. Son dignas de revisión, pero no tan fuertes como las sondas nativas directas."'),
        ('"This detector relies mostly on JNI-backed native probes. Native coverage was unavailable on this build, and the remaining runtime checks stayed clean."',
         '"Este detector depende principalmente de sondas nativas JNI. La cobertura nativa no estuvo disponible en este build, y las verificaciones de runtime restantes permanecieron limpias."'),
        ('"KernelSU read-only supercall, prctl-side probes, KernelPatch side channel, self-process IOC, isolated-process mount drift, manager manifest fingerprint, SUSFS side-channel, /data/adb artifacts, curated tmp/system/storage residue paths, /data/local/tmp metadata, root-process audit, cgroup/process leakage, kernel strings, and properties stayed clean."',
         '"Las sondas supercall de KernelSU, prctl, canal lateral KernelPatch, IOC de proceso propio, deriva de montaje aislado, fingerprint del manifest, canal lateral SUSFS, artefactos /data/adb, rutas de residuo curadas, metadatos /data/local/tmp, auditoría de procesos root, fugas cgroup, strings del kernel y propiedades permanecieron limpios."'),
        ('"Blocked by seccomp"', '"Bloqueado por seccomp"'),
        ('"The sacrificial reboot() helper died under app seccomp before it could install a temporary [ksu_driver] fd. Other KernelSU checks still ran."',
         '"El proceso helper reboot() sacrificial terminó bajo seccomp antes de poder instalar un fd [ksu_driver] temporal. Otras verificaciones de KernelSU continuaron."'),
        ('"Self process IOC"', '"IOC de proceso propio"'),
        ('"Isolated mount drift"', '"Deriva de montaje aislado"'),
        ('"Manager fingerprint"', '"Fingerprint del manager"'),
        ('"Runtime paths"', '"Rutas de runtime"'),
        ('"Root processes"', '"Procesos root"'),
        ('"Cgroup leakage"', '"Fuga cgroup"'),
        ('"Kernel symbols"', '"Símbolos del kernel"'),
        ('"Kernel modules"', '"Módulos del kernel"'),
        ('"Kernel identity"', '"Identidad del kernel"'),
        ('"Root-specific properties"', '"Propiedades específicas de root"'),
        ('"Paths checked"', '"Rutas verificadas"'),
        ('"Path hits"', '"Detecciones de ruta"'),
        ('"Proc checked"', '"Procs verificados"'),
        ('"Proc denied"', '"Procs denegados"'),
        ('"Proc hits"', '"Detecciones de proc"'),
        ('"Self driver FDs"', '"FDs driver propios"'),
        ('"Self wrapper FDs"', '"FDs wrapper propios"'),
        ('"Main mnt ns"', '"NS montaje principal"'),
        ('"Isolated mnt ns"', '"NS montaje aislado"'),
        ('"Mount drift hits"', '"Detecciones deriva montaje"'),
        ('"Mount anchor drifts"', '"Derivas de anclaje de montaje"'),
        ('"Manager traits"', '"Rasgos del manager"'),
        ('"Cgroup paths"', '"Rutas cgroup"'),
        ('"Cgroup visible"', '"Cgroup visible"'),
        ('"Cgroup proc"', '"Proc cgroup"'),
        ('"Cgroup denied"', '"Cgroup denegado"'),
        ('"Cgroup hits"', '"Detecciones cgroup"'),
        ('"Kernel sources"', '"Fuentes del kernel"'),
        ('"Kernel hits"', '"Detecciones del kernel"'),
        ('"Properties checked"', '"Propiedades verificadas"'),
        ('"Property hits"', '"Detecciones de propiedades"'),
        ('"Isolated-process mount drift, manager manifest fingerprints, kernel strings, property residue, or cgroup leakage can indicate native-root history or selective runtime hiding, but they are weaker than direct syscall-side probes."',
         '"La deriva de montaje de proceso aislado, fingerprints del manifest del manager, strings del kernel, residuos de propiedades o fugas cgroup pueden indicar historial root nativo, pero son más débiles que las sondas directas a nivel syscall."'),
        ('"No common KernelSU, APatch, Magisk, SUSFS, or cgroup-leak traces surfaced from the current probe set."',
         '"No surgieron trazas comunes de KernelSU, APatch, Magisk, SUSFS ni fugas cgroup del conjunto de sondas actual."'),
        ('"A determined root can still hide or remove residue, so absence of native hits is not proof of a stock device."',
         '"Un root determinado puede ocultar o eliminar residuos, por lo que la ausencia de detecciones nativas no prueba que el dispositivo sea original."'),
        ('"Native coverage was unavailable, so this card should not be treated as a strong clean verdict."',
         '"La cobertura nativa no estuvo disponible, por lo que esta tarjeta no debe tratarse como un veredicto limpio fuerte."'),
    ],
    # BootloaderCardModelMapper
    f"{BASE}/features/bootloader/presentation/BootloaderCardModelMapper.kt": [
        ('"attestation + boot props + raw boot consistency"', '"attestation + props de boot + consistencia de boot"'),
        ('"local bootloader scan failed"', '"escaneo local de bootloader fallido"'),
        ('"Scanning boot state and verified boot evidence"', '"Escaneando estado de boot y evidencia de boot verificado"'),
        ('"Locked by boot properties"', '"Bloqueado por propiedades de boot"'),
        ('"Locked state without full proof"', '"Estado bloqueado sin prueba completa"'),
        ('"Boot state inconclusive"', '"Estado de boot inconcluso"'),
        ('"Unlocked state, attestation contradictions, broken certificate trust, or verified-boot failures indicate reduced boot-chain trust."',
         '"Estado desbloqueado, contradicciones de attestation, confianza de certificado rota o fallos de verified-boot indican confianza reducida en la cadena de boot."'),
        ('"The boot chain is not obviously broken, but the evidence still shows custom-root, software-only, or coherence signals worth reviewing."',
         '"La cadena de boot no está obviamente rota, pero la evidencia aún muestra señales de root personalizado, solo software o coherencia que vale la pena revisar."'),
        ('"Boot properties look conservative, but the result falls back to software-readable signals because attestation RootOfTrust was unavailable."',
         '"Las propiedades de boot parecen conservadoras, pero el resultado cae de vuelta a señales legibles por software porque el RootOfTrust de attestation no estuvo disponible."'),
        ('"Unlocked bootloaders allow custom boot images and can disable or bypass normal verified-boot guarantees."',
         '"Los bootloaders desbloqueados permiten imágenes de boot personalizadas y pueden desactivar o eludir las garantías normales de boot verificado."'),
        ('"Verified Boot failure means the boot chain reported a critical verification problem, which is stronger than a normal custom-ROM signal."',
         '"El fallo de Verified Boot significa que la cadena de boot reportó un problema crítico de verificación, más fuerte que una señal normal de ROM personalizada."'),
        ('"Self-signed verified boot usually means the bootloader is re-locked against a user-managed key rather than the OEM root of trust."',
         '"El boot verificado auto-firmado generalmente significa que el bootloader está re-bloqueado contra una clave gestionada por el usuario en lugar del root of trust del OEM."'),
        ('"Attestation-vs-runtime contradictions are higher confidence than a single suspicious property because hardware-backed and software-readable boot evidence disagree."',
         '"Las contradicciones entre attestation y runtime tienen mayor confianza que una sola propiedad sospechosa porque la evidencia de boot respaldada por hardware y la legible por software no coinciden."'),
        ('"Samsung Knox warranty e-fuse appears tripped, which is permanent on supported Samsung devices and often reflects prior unlocking or unofficial boot images."',
         '"El e-fuse de garantía Samsung Knox parece activado, lo cual es permanente en dispositivos Samsung compatibles y frecuentemente refleja desbloqueos previos o imágenes de boot no oficiales."'),
        ('"Debuggable or insecure build flags reduce confidence in software-readable boot signals and are not normal for production user builds."',
         '"Los flags de build depurables o inseguros reducen la confianza en las señales de boot legibles por software y no son normales en builds de producción."'),
        ('"This result relies on boot properties only. Root or property-hook layers can spoof these values more easily than attestation RootOfTrust."',
         '"Este resultado depende solo de propiedades de boot. Las capas de root o property-hook pueden falsificar estos valores más fácilmente que el RootOfTrust de attestation."'),
        ('"No bootloader or verified-boot signal suggested an unlocked or obviously contradictory boot chain."',
         '"Ninguna señal de bootloader o verified-boot sugirió una cadena de boot desbloqueada o obviamente contradictoria."'),
        ('"No rows were produced for this section on this device."', '"No se generaron filas para esta sección en este dispositivo."'),
        ('label = "Proof"', 'label = "Prueba"'),
        ('label = "Tier"', 'label = "Nivel"'),
        ('BootloaderHeaderFactModel("State"', 'BootloaderHeaderFactModel("Estado"'),
        ('BootloaderHeaderFactModel("Proof"', 'BootloaderHeaderFactModel("Prueba"'),
        ('BootloaderHeaderFactModel("Tier"', 'BootloaderHeaderFactModel("Nivel"'),
        ('BootloaderHeaderFactModel("Trust"', 'BootloaderHeaderFactModel("Confianza"'),
        ('"Properties checked"', '"Propiedades verificadas"'),
        ('"Properties observed"', '"Propiedades observadas"'),
        ('"Native hits"', '"Detecciones nativas"'),
        ('"Raw boot hits"', '"Detecciones boot raw"'),
        ('"Source mismatches"', '"Discrepancias de fuente"'),
        ('"Attestation chain"', '"Cadena de attestation"'),
        ('"Hardware-backed"', '"Respaldado por hardware"'),
        ('"Key attestation"', '"Attestation de clave"'),
        ('"Certificate trust"', '"Confianza de certificado"'),
        ('"Boot consistency"', '"Consistencia de boot"'),
        ('"Property catalog"', '"Catálogo de propiedades"'),
        ('"Raw boot params"', '"Parámetros de boot raw"'),
        ('"Source consistency"', '"Consistencia de fuente"'),
        ('"Cross-check rules"', '"Reglas de cruce"'),
        ('value = if (report.hardwareBacked) "Yes" else "No"', 'value = if (report.hardwareBacked) "Sí" else "No"'),
        ('BootloaderEvidenceMode.ATTESTATION -> "Attest"', 'BootloaderEvidenceMode.ATTESTATION -> "Attestation"'),
        ('BootloaderEvidenceMode.PROPERTIES_ONLY -> "Props"', 'BootloaderEvidenceMode.PROPERTIES_ONLY -> "Props"'),
        ('BootloaderState.VERIFIED -> "Verified"', 'BootloaderState.VERIFIED -> "Verificado"'),
        ('BootloaderState.SELF_SIGNED -> "Custom"', 'BootloaderState.SELF_SIGNED -> "Personalizado"'),
        ('BootloaderState.UNLOCKED -> "Unlocked"', 'BootloaderState.UNLOCKED -> "Desbloqueado"'),
        ('BootloaderState.LOCKED_UNKNOWN -> "Locked?"', 'BootloaderState.LOCKED_UNKNOWN -> "¿Bloqueado?"'),
        ('TeeTrustRoot.FACTORY -> "Factory"', 'TeeTrustRoot.FACTORY -> "Fábrica"'),
    ],
    # DangerousAppsCardModelMapper
    f"{BASE}/features/dangerousapps/presentation/DangerousAppsCardModelMapper.kt": [
        ('"Scanning app inventory"', '"Escaneando inventario de apps"'),
        ('"Inventory scan failed"', '"Escaneo de inventario fallido"'),
        ('"HMA-style concealment detected"', '"Ocultamiento estilo HMA detectado"'),
        ('"Shared storage baseline denied"', '"Línea base de almacenamiento compartido denegada"'),
        ('"Package inventory unusually small"', '"Inventario de paquetes inusualmente pequeño"'),
        ('"Multiple fixed shared-storage baseline paths returned EACCES/EPERM under stat(). This suggests shared user gid or related zygote storage groups may have been restricted."',
         '"Múltiples rutas de línea base de almacenamiento compartido devolvieron EACCES/EPERM bajo stat(). Esto sugiere que el gid de usuario compartido o grupos de almacenamiento zygote relacionados pueden estar restringidos."'),
        ('label = "Targets"', 'label = "Objetivos"'),
        ('label = "Hits"', 'label = "Detecciones"'),
        ('label = "Hidden"', 'label = "Ocultos"'),
        ('ContextItemModel("Categories"', 'ContextItemModel("Categorías"'),
        ('ContextItemModel("Probe families"', 'ContextItemModel("Familias de sondas"'),
        ('DangerousPackageVisibility.RESTRICTED -> "Scoped"', 'DangerousPackageVisibility.RESTRICTED -> "Limitado"'),
        ('DangerousPackageVisibility.FULL -> "Full inventory access"', 'DangerousPackageVisibility.FULL -> "Acceso completo al inventario"'),
        ('DangerousPackageVisibility.RESTRICTED -> "Scoped inventory access"', 'DangerousPackageVisibility.RESTRICTED -> "Acceso limitado al inventario"'),
        ('DangerousPackageVisibility.UNKNOWN -> "Not resolved yet"', 'DangerousPackageVisibility.UNKNOWN -> "No resuelto aún"'),
        ('"Inventory"', '"Inventario"'),
    ],
    # DangerousAppsDetectorCard
    f"{BASE}/features/dangerousapps/ui/card/DangerousAppsDetectorCard.kt": [
        ('"View target apps (${count})"', '"Ver apps objetivo (${count})"'),
        ('"legacy targets"', '"objetivos legacy"'),
        ('"full PM inventory"', '"inventario PM completo"'),
        ('"visible"', '"visible"'),
    ],
    # BootloaderRepository
    f"{BASE}/features/bootloader/data/repository/BootloaderRepository.kt": [
        ('"Boot state"', '"Estado de boot"'),
        ('"Evidence source"', '"Fuente de evidencia"'),
        ('"Lock state"', '"Estado de bloqueo"'),
        ('"Trust root"', '"Raíz de confianza"'),
        ('"Attestation tier"', '"Nivel de attestation"'),
        ('"Certificate chain"', '"Cadena de certificados"'),
        ('"Attested boot state"', '"Estado de boot atestiguado"'),
        ('"Attested deviceLocked"', '"deviceLocked atestiguado"'),
        ('"Attested hash vs vbmeta digest"', '"Hash atestiguado vs digest vbmeta"'),
        ('"Verified state coherence"', '"Coherencia de estado verificado"'),
        ('"Property source mismatch"', '"Discrepancia de fuente de propiedad"'),
        ('"Key attestation"', '"Attestation de clave"'),
        ('"Certificate trust"', '"Confianza de certificado"'),
        ('"Boot consistency"', '"Consistencia de boot"'),
        ('"Property catalog"', '"Catálogo de propiedades"'),
        ('"Raw boot params"', '"Parámetros de boot raw"'),
        ('"Source consistency"', '"Consistencia de fuente"'),
        ('"Cross-check rules"', '"Reglas de cruce"'),
        ('"Properties checked"', '"Propiedades verificadas"'),
        ('"Properties observed"', '"Propiedades observadas"'),
        ('"Native hits"', '"Detecciones nativas"'),
        ('"Raw boot hits"', '"Detecciones boot raw"'),
        ('"Source mismatches"', '"Discrepancias de fuente"'),
        ('"Attestation chain"', '"Cadena de attestation"'),
        ('"Hardware-backed"', '"Respaldado por hardware"'),
        ('"RootOfTrust data was available and took priority over software-readable properties."',
         '"Los datos de RootOfTrust estuvieron disponibles y tuvieron prioridad sobre las propiedades legibles por software."'),
        ('"Attestation root data was unavailable, so this result falls back to boot properties that can be modified on rooted systems."',
         '"Los datos de raíz de attestation no estuvieron disponibles; este resultado cae de vuelta a propiedades de boot que pueden modificarse en sistemas rooteados."'),
        ('"Neither attestation RootOfTrust nor readable boot properties were available."',
         '"Ni el RootOfTrust de attestation ni las propiedades de boot legibles estuvieron disponibles."'),
        ('"Locked"', '"Bloqueado"'),
        ('"Unlocked"', '"Desbloqueado"'),
        ('"Failed"', '"Fallido"'),
        ('"Valid"', '"Válida"'),
        ('"Broken"', '"Rota"'),
        ('"Certificate chain length: ${trust.chainLength}. Challenge matched generated nonce."',
         '"Longitud de cadena de certificados: ${trust.chainLength}. Challenge coincide con el nonce generado."'),
        ('"RootOfTrust.verifiedBootState from attestation extension."', '"RootOfTrust.verifiedBootState de la extensión de attestation."'),
        ('"RootOfTrust.deviceLocked from attestation extension."', '"RootOfTrust.deviceLocked de la extensión de attestation."'),
        ('"Mismatch"', '"Discrepancia"'),
        ('"Digest missing"', '"Digest faltante"'),
        ('"All zeros"', '"Todo ceros"'),
        ('"Impossible pair"', '"Par imposible"'),
        ('"Aligned"', '"Alineado"'),
        ('"Partial"', '"Parcial"'),
        ('"Tracked boot, AVB, dm-verity, Samsung fuse, and secure-build properties."', '"Propiedades de boot, AVB, dm-verity, fuse Samsung y build seguro rastreadas."'),
        ('"android.os.SystemProperties reflection reads for tracked boot properties."', '"Lecturas de reflexión de android.os.SystemProperties para propiedades de boot rastreadas."'),
        ('"Single getprop dump reused for cross-source comparisons."', '"Volcado único de getprop reutilizado para comparaciones entre fuentes."'),
        ('"Native libc property cross-checks using the callback-based system property API."', '"Cruces de propiedades nativas libc usando la API de propiedades del sistema basada en callbacks."'),
        ('"androidboot.* values from /proc/cmdline and /proc/bootconfig."', '"Valores androidboot.* de /proc/cmdline y /proc/bootconfig."'),
        ('"Fallback only"', '"Solo respaldo"'),
        ('"No chain"', '"Sin cadena"'),
        ('"Invalid"', '"Inválida"'),
        ('"Anomaly"', '"Anomalía"'),
        ('"RootOfTrust availability: ${attestation.rootOfTrust != null}."', '"Disponibilidad de RootOfTrust: ${attestation.rootOfTrust != null}."'),
        ('"Key attestation did not expose a usable certificate chain."', '"La attestation de clave no expuso una cadena de certificados usable."'),
        ('"Failed"', '"Fallido"'),
        ('"Unavailable"', '"No disponible"'),
    ],
}

total_files = 0
total_changes = 0

for filepath, replacements in files.items():
    if not os.path.exists(filepath):
        print(f"SKIP (no existe): {filepath}")
        continue
    with open(filepath, encoding="utf-8") as f:
        content = f.read()
    original = content
    local = 0
    for old, new in replacements:
        if old in content:
            content = content.replace(old, new)
            local += 1
    if content != original:
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(content)
        total_files += 1
        total_changes += local
        fname = os.path.basename(filepath)
        print(f"  {fname}: {local} cambios")
    else:
        fname = os.path.basename(filepath)
        print(f"  {fname}: 0 cambios (verificar strings)")

print(f"\nTotal: {total_files} archivos, {total_changes} reemplazos")
